export enum ResumeConstants {
  FETCH_RESUME_DATA_REQUEST = "FETCH_RESUME_DATA_REQUEST",
  FETCH_RESUME_DATA_SUCCESS = "FETCH_RESUME_DATA_SUCCESS",
  FETCH_RESUME_DATA_FAILED = "FETCH_RESUME_DATA_FAILED"
}
