export enum ProjectConstants {
  FETCH_PROJECT_DATA_REQUEST = "FETCH_PROJECT_DATA_REQUEST",
  FETCH_PROJECT_DATA_SUCCESS = "FETCH_PROJECT_DATA_SUCCESS",
  FETCH_PROJECT_DATA_FAILED = "FETCH_PROJECT_DATA_FAILED"
};
