export const FETCH_PROFILE_DATA_REQUEST = "FETCH_PROFILE_DATA_REQUEST";
export const FETCH_PROFILE_DATA_SUCCESS = "FETCH_PROFILE_DATA_SUCCESS";
export const FETCH_PROFILE_DATA_FAILED = "FETCH_PROFILE_DATA_FAILED";
